Controllers/GridController.cs
using Microsoft.AspNetCore.Mvc;

namespace TestTaskOnSea.Controllers
{
    public class GridController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult PlayGame()
        {
            return View();
        }
    }
}

Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using TestTaskOnSea.Models;
using TestTaskOnSea.UnitOfWork.Interfaces;

namespace TestTaskOnSea.Controllers
{
    public class UserController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public UserController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult SignUp()
        {
            return View();
        }
        [HttpGet]
        public IActionResult SignIn()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SignUp(User user)
        {
            _unitOfWork.userRepository.AddUser(user);
            await _unitOfWork.SaveAsync();
            return RedirectToAction("SignIn");
        }
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            var users = await _unitOfWork.userRepository.GetAllAsync();
            return Ok(users);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TestTaskOnSea</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/bootsWatchTheme.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TestTaskOnSea.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <div class="container-fluid">
            <a class="navbar-brand" href="#">Navbar</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse d-flex justify-content-center" id="navbarColor03">
              <ul class="navbar-nav">
                <li class="nav-item">
                 <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link text-dark" asp-area="" asp-controller="Grid" asp-action="Index">Play Game</a>
                </li>
              </ul>
            </div>
            <div class="collapse navbar-collapse d-flex justify-content-end" id="navbarColor03">
              <ul class="navbar-nav">
                <li class="nav-item">
                  <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="SignIn">SignIn</a>
                </li>
              </ul>
            </div>
          </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - TestTaskOnSea - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>